.TH VUSH 1 "" "vush"
.SH NAME
vush \- simple UNIX shell
.SH SYNOPSIS
.B vush
.RI [ scriptfile ]
.SH DESCRIPTION
vush is a lightweight UNIX shell supporting command execution,
pipelines, command chaining with ';', '&&' and '||',
environment variable expansion (with "$?" storing the last exit status),
wildcard matching for '*' and '?', and background jobs.  When a
\fIscriptfile\fP is supplied, commands are read from that file
instead of standard input.  A `#` outside of quotes begins a comment
and causes the rest of the line to be ignored.
.SH OPTIONS
None.
.SH BUILTINS
.TP
.B cd [dir]
Change the current directory. Without an argument it switches to \fB$HOME\fP.
After a successful change \fB$PWD\fP and \fB$OLDPWD\fP are updated. Using
\fBcd -\fP prints and switches to \fB$OLDPWD\fP.
.TP
.B exit
Exit the shell.
.TP
.B pwd
Print the current working directory.
.TP
.B jobs
List running background jobs.
.TP
.B fg ID
Wait for job ID in the foreground.
.TP
.B kill [-SIGNAL] ID
Send a signal to job ID.
.TP
.B export NAME=value
Set an environment variable for the shell.
.TP
.B unset \fIname\fP
Remove an environment variable.
.TP
.B history
Show command history.
.TP
.B alias \fIname\fP=\fIvalue\fP
Set an alias or list aliases when used without arguments.
.TP
.B unalias \fIname\fP
Remove an alias.
.TP
.B source \fIfile\fP
Read commands from \fIfile\fP.
.TP
.B . \fIfile\fP
Alias for \fBsource\fP.
.TP
.B help
Display information about built-in commands.
.SH SEE ALSO
README.md
